# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Beijing PM2.5 Data Set
email: thfong2@illinois.edu
author: Titus Fong
description: > # "Write an awesome description for your new site here. 
    Data visualization project in Beijing's Pm2.5 measurement from 2010 to 2015 and its pollution reduction target.
copyright: 'Copyright &copy; 2017 Titus Fong. All Rights Reserved.'
#credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: linkedin
    url: https://www.linkedin.com/in/titus-fong-33a2bb55/
page:
  - title: Is Beijing achieving its Pm2.5 pollution reduction target?